---
# yaml-language-server: $schema=https://schema.blue-build.org/module-list-v1.json
modules:
  - type: systemd
    system:
      enabled:
        - tailscaled.service
    user:
      enabled:
        - dms.service
        - podman.socket
