---
# yaml-language-server: $schema=https://schema.blue-build.org/module-list-v1.json
modules:
  - type: systemd
    system:
      enabled:
        - greetd.service
        - tailscaled.service
    user:
      enabled:
        - dms.service
        - dsearch.service
        - gnome-keyring-daemon.service
        - gnome-keyring-daemon.socket
        - podman.socket
        - ssh-agent.socket
        - udiskie.service
